#!/usr/bin/env python3
"""Reporting + reproducibility CLI.

Pre-Stage-A:  contract | preflight   -> outputs/{dataset}/contract/
Stage E:      seg_table | ablation_table
Stage F:      repro_pack | hash_ckpts
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from datetime import date
from glob import glob
from pathlib import Path

import pandas as pd

from config import (
    add_global_stage_args,
    config_chain as _config_chain,
    ensure_dir,
    load_config,
    stage_run_dir,
)
from data import frozen_split_path

CONTRACT = """# Study contract — {dataset_title}

Locked: {today}
Config: `{config_path}`
Config SHA-256: `{config_sha}`

> Pre-registration. This file records what was committed to *before* Stage A
> ran; it is deliberately not regenerated by later stages. Re-running
> `stage_report.py contract` refuses to overwrite it without `--force`, so the
> lock date and config hash stay meaningful. Whether the commitments below are
> actually satisfied on disk is a separate question, answered by
> `stage_report.py preflight`.

## Primary claim
- One-sentence framing finalized (empirical fusion-strategy comparison, not a proposed method)

Dataset: **{dataset}**. Part labels: {part_labels}.
This is a controlled empirical comparison, not a new-architecture paper: a part
segmenter is trained once on the annotated part set and frozen; every comparison arm
(whole-image, body-masked, part-crop late fusion, multi-task, attention-pooled part
fusion, concatenation, and gated residual fusion, each with an
optional classical + learned-IQA descriptor branch) is trained under an identical
protocol on the same backbones, splits, and epoch budget, and differs only in how it
combines visual evidence. No arm is privileged as "the method"; the contribution is
the comparison itself, reported with multi-seed confidence intervals and paired
significance tests.

## Data
- Dataset locked: `{dataset}`
- Part–whole root locked: `{partwhole}`
- Large classification root locked: `{large}`
- Part labels: {part_labels}
- Split policy: `{split_policy}` (freeze / official CSV on **original GT**)
- Input resolution: segmentation {image_size}px, classification {cls_image_size}px
  (segmentation input must be divisible by 32 for the SMP sweep)
- Learned NR-IQA branch: {iqa_metrics}
- Stage A train-only 6× geometric aug (`train_aug_images`/`train_aug_masks`; val/test never augmented)
- Splits under: `{output_root}/frozen_splits/` ({split_file}; CLS: {cls_split_file})

## Comparison arms (must-have — every arm run under the same protocol)
- Whole-image CNN/ViT reference ({n_backbones} reference-aligned backbones): {backbones}
- Whole-image, capacity-matched control (isolates the parameter-count confound)
- Whole-image, heavy-augmentation control (isolates the regularization confound)
- Body-masked / full-body
- Part-crop late fusion (GT + predicted + confidence-gated pseudo masks)
- Attention-pooled part fusion (same crops as late fusion, different aggregation)
- Multi-task seg+cls
- Descriptor fusion arms: {fusion_modes}
- Confidence-weighted vs. unweighted descriptor aggregation (evaluated ablation, not a proposed method)
- Cite the strongest prior-work numbers for this dataset for context only

## Reporting requirements
- >= 3 seeds per (arm, mask source) cell; bootstrap 95% CI + paired significance vs. whole-image reference
- Long-tail frequency-bin stratification (not overall accuracy alone)
- Expected Calibration Error + selective-prediction (AURC) per arm
- Synthetic-corruption robustness sweep on the strongest 2-3 arms
- Params / FLOPs / latency logged per arm (accuracy-per-compute framing)
- Checkpoint SHA-256 + seed recorded in every run_meta.json

## Success criteria
[ ] Macro-F1 Δ over whole-image baseline, per arm, with 95% CI: ____  *(fill after Stage B)*
[ ] Rare-bin (<5) Δ, per arm: ____  *(fill after Stage B)*
[ ] Latency budget (ms/img), per arm: ____
[ ] Does any arm's advantage survive the capacity-matched / heavy-aug controls?: ____

## Official backbones
{backbone_list}

## Metrics (locked)
- Primary: {metrics}
- Long-tail bins: {bins}
- Segmentation: val/test mIoU + per-part IoU ({part_labels});
  pick default Stage A model by **val mIoU**
"""

def cmd_seg_table(cfg, summary: str | None, out: str):
    summary_path = (
        Path(summary)
        if summary
        else Path(cfg["paths"]["output_root"]) / "stage_a" / "sweep_summary.json"
    )
    if not summary_path.exists():
        raise SystemExit(f"Missing {summary_path}")

    rows = json.loads(summary_path.read_text(encoding="utf-8"))
    labels = list(cfg.get("part_labels") or [])
    show = labels if labels else ["background", "part1", "part2", "part3"]

    # Both IoU definitions, always. They are not interchangeable and the
    # difference is large: macro mIoU averages per-class IoU (so CUB's rare
    # legs/eyes count as much as background), while `dataset_iou` is smp's
    # reduction="micro" -- pooled over all pixels, hence background-dominated,
    # and the one prior work reports. On CUB the same checkpoint scores 0.5610
    # macro and 0.8978 micro. Emitting only the macro number made the Stage A
    # table read as a 40-point regression against a paper that had simply
    # measured something else.
    header = (
        "| arch | encoder | backend | val mIoU | test mIoU | "
        "val datasetIoU | test datasetIoU | "
        + " | ".join(f"val {l}" for l in show)
        + " | "
        + " | ".join(f"test {l}" for l in show)
        + " |"
    )
    sep = "|---|---|---|---:|---:|---:|---:|" + "|".join(["---:"] * (2 * len(show))) + "|"
    lines = [header, sep]
    for r in rows:
        vp = r.get("val_per_part_iou") or {}
        tp = r.get("test_per_part_iou") or {}

        def g(d, k):
            v = d.get(k)
            return f"{v:.4f}" if isinstance(v, (int, float)) else ""

        def f(x):
            return f"{x:.4f}" if isinstance(x, (int, float)) else ""

        cells = [
            str(r.get("arch", "")),
            str(r.get("encoder", "")),
            str(r.get("backend", "")),
            f(r.get("val_miou")),
            f(r.get("test_miou")),
            f(r.get("val_dataset_iou")),
            f(r.get("test_dataset_iou")),
        ]
        for lab in show:
            cells.append(g(vp, lab))
        for lab in show:
            cells.append(g(tp, lab))
        lines.append("| " + " | ".join(cells) + " |")
    lines.append("")
    lines.append(
        "mIoU is the macro mean of per-class IoU (`reduction=\"none\"`, then "
        "`nanmean`). datasetIoU is smp's `reduction=\"micro\"`, pooled over all "
        "pixels and therefore background-dominated; it is reported because "
        "prior work (Choton et al., 2026) uses that definition, and the two are "
        "not comparable to each other."
    )
    md = "\n".join(lines) + "\n"
    out_path = Path(out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(md, encoding="utf-8")
    print(md)
    print(f"Wrote {out_path}")


PROVENANCE_EQUIVALENCE_PATH = Path(__file__).resolve().parent / "provenance_equivalence.yaml"


def _load_equivalences(dataset: str | None, path: Path | None = None) -> list[dict]:
    """Declared-equivalent `code_version` stamps for `dataset`.

    See provenance_equivalence.yaml. Returns [] when the file is absent, so a
    checkout without one behaves exactly as before this existed.
    """
    path = path or PROVENANCE_EQUIVALENCE_PATH
    if dataset is None or not Path(path).is_file():
        return []
    import yaml

    doc = yaml.safe_load(Path(path).read_text(encoding="utf-8")) or {}
    return [
        e for e in (doc.get("equivalences") or [])
        if e.get("dataset") == dataset and e.get("stamps")
    ]


def _apply_equivalences(df, equivalences: list[dict]):
    """Collapse each declared group of stamps to its `canonical` value.

    Returns (frame, notes). The frame is a copy -- the summary CSV on disk keeps
    the stamps the runs actually recorded, because the declaration is a
    judgement ABOUT that record and must not overwrite it.
    """
    notes = []
    if not equivalences or "code_version" not in df.columns:
        return df, notes
    df = df.copy()
    for entry in equivalences:
        stamps = [str(x) for x in entry["stamps"]]
        canonical = str(entry.get("canonical") or stamps[0])
        hit = df["code_version"].astype(str).isin(stamps)
        if not hit.any():
            continue
        df.loc[hit, "code_version"] = canonical
        notes.append(
            f"{int(hit.sum())} row(s) had their code_version collapsed to "
            f"`{canonical}` under the equivalence declared "
            f"{entry.get('declared', 'undated')} in "
            f"{PROVENANCE_EQUIVALENCE_PATH.name}: "
            + " ".join(str(entry.get("reason", "")).split())
        )
    return df, notes


def _enforce_single_provenance(df, allow_mixed: bool, equivalences: list[dict] | None = None):
    """Refuse to aggregate rows produced by different code.

    A comparison table is only a comparison if every cell was computed the same
    way. In August 2026 this table averaged rows from before and after the
    descriptor z-scoring fix: pre-fix, the fusion head's LayerNorm was dominated
    by raw `*_area` columns and the visual branch reached the classifier as a
    near-constant, so `concat` reproduced `descriptors_only` seed for seed.
    Those rows sat in the same table as post-fix rows with nothing to
    distinguish them, and the published table mixed both for five days.

    Two independent stamps are checked. `desc_standardized` is the specific
    marker that fix introduced; the code stamp is the general one and catches
    every future change of the same shape. The code stamp is `source_digest`
    (a content hash of the modules and config that determine a number) when
    every row carries one, falling back to `code_version` for rows written
    before digests existed.
    """
    problems = []
    df, equivalence_notes = _apply_equivalences(df, equivalences or [])
    for note in equivalence_notes:
        print(f"[ablation_table] {note}")
    if "desc_standardized" in df.columns:
        desc_modes = {"concat", "gated_residual", "attention_parts", "descriptors_only"}
        affected = df[df["mode"].isin(desc_modes)] if "mode" in df.columns else df
        stale = affected[affected["desc_standardized"] != True]  # noqa: E712
        if len(stale):
            problems.append(
                f"{len(stale)} descriptor-arm row(s) lack desc_standardized=True, "
                "i.e. they predate the descriptor z-scoring fix and are not "
                "comparable to rows that carry it."
            )
    # `source_digest` is authoritative when every row carries one: it hashes the
    # contents of the modules and config that determine a number, so it is
    # unchanged by a commit that edits no file and differs between two working
    # trees that git would both label `-dirty`. `code_version` is the fallback
    # for rows written before digests existed, and it is only a proxy -- see
    # config.code_version for the two ways it misreports.
    have_digest = "source_digest" in df.columns and not df["source_digest"].isna().any()
    stamp_col = "source_digest" if have_digest else "code_version"
    if stamp_col in df.columns:
        versions = sorted(str(v) for v in df[stamp_col].dropna().unique())
        if len(versions) > 1:
            problems.append(f"rows span {len(versions)} code versions ({stamp_col}): {versions}")
        if df[stamp_col].isna().any():
            problems.append(
                f"{int(df[stamp_col].isna().sum())} row(s) carry no {stamp_col} "
                "(written before provenance stamping)."
            )
    if not problems:
        return df, equivalence_notes
    msg = "[ablation_table] mixed provenance:\n  - " + "\n  - ".join(problems)
    if not allow_mixed:
        raise SystemExit(
            msg
            + "\n\nRe-run the affected cells, or pass --allow_mixed to build the "
            "table anyway (the result is not a controlled comparison)."
        )
    print(msg + "\n[ablation_table] --allow_mixed set; continuing.")
    return df, equivalence_notes + [
        "Built with --allow_mixed over the objection above; this table is NOT a "
        "controlled comparison. " + " ".join(msg.split())
    ]


def cmd_ablation_table(
    fusion_summary: str,
    out: str,
    reference_mode: str = "concat",
    n_boot: int = 2000,
    allow_mixed: bool = False,
    dataset: str | None = None,
):
    """Aggregate the per-seed fusion_ablation_summary.csv into a comparison
    table with bootstrap 95% CIs and, when >1 seed is present, a paired
    significance test of every arm against `reference_mode` (default:
    concatenation, the simplest deep-fusion arm) within each (group,
    mask_source) cell. With a single seed, only point estimates are shown —
    the CI/p-value columns are left blank rather than fabricated.
    """
    from metrics import bootstrap_ci, paired_bootstrap_test

    df = pd.read_csv(fusion_summary)
    df, provenance_notes = _enforce_single_provenance(
        df, allow_mixed, _load_equivalences(dataset)
    )
    group_cols = [c for c in ["mode", "group", "mask_source", "backbone"] if c in df.columns]

    # Stage B writes "n/a" for the group / mask_source of arms that have
    # neither (baseline, capacity_matched, heavy_aug, multitask). "n/a" is in
    # pandas' default NA list, so it round-trips out of the CSV as NaN -- and
    # `groupby` drops NaN keys by default. That silently deleted every
    # non-fusion arm from this table, including the whole-image reference that
    # every other arm is supposed to be compared against: 10 rows in, 2 rows
    # out. Restore the sentinel before grouping.
    for col in group_cols:
        df[col] = df[col].fillna("n/a")

    has_seed = "seed" in df.columns and df["seed"].nunique() > 1

    rows = []
    for keys, g in df.groupby(group_cols):
        keys = keys if isinstance(keys, tuple) else (keys,)
        row = dict(zip(group_cols, keys))
        for metric in ["top1", "top3", "macro_f1"]:
            if metric not in g.columns:
                continue
            ci = bootstrap_ci(g[metric].to_numpy(), n_boot=n_boot)
            row[f"{metric}_mean"] = round(ci["mean"], 4)
            row[f"{metric}_ci95"] = (
                f"[{ci['lo']:.4f}, {ci['hi']:.4f}]" if has_seed and ci["n"] > 1 else ""
            )
        row["n_seeds"] = int(g["seed"].nunique()) if "seed" in g.columns else 1
        for extra in ["n_params", "backbone_passes_per_image"]:
            if extra in g.columns:
                row[extra] = g[extra].iloc[0]
        rows.append(row)
    out_df = pd.DataFrame(rows)

    if has_seed and "mode" in df.columns and reference_mode in df["mode"].unique():
        sig_col = []
        for _, row in out_df.iterrows():
            other_keys = {c: row[c] for c in group_cols if c != "mode"}
            ref_mask = (df["mode"] == reference_mode)
            for c, v in other_keys.items():
                ref_mask &= df[c] == v
            arm_mask = df["mode"] == row["mode"]
            for c, v in other_keys.items():
                arm_mask &= df[c] == v
            if row["mode"] == reference_mode or ref_mask.sum() < 2 or arm_mask.sum() < 2:
                sig_col.append("")
                continue
            # Pair by seed identity, not row position: if a middle seed failed
            # for only one of the two arms, positional truncation would
            # silently compare mismatched seeds (e.g. arm's seed=77 vs.
            # reference's seed=42). An inner merge on `seed` keeps only the
            # seeds both arms actually share.
            arm_seeds = df.loc[arm_mask, ["seed", "top1"]].drop_duplicates("seed", keep="last")
            ref_seeds = df.loc[ref_mask, ["seed", "top1"]].drop_duplicates("seed", keep="last")
            paired = arm_seeds.merge(ref_seeds, on="seed", suffixes=("_arm", "_ref"))
            if len(paired) < 2:
                sig_col.append("")
                continue
            if set(arm_seeds["seed"]) != set(ref_seeds["seed"]):
                print(
                    f"[ablation_table] WARNING: {row['mode']} vs {reference_mode} "
                    f"({dict(other_keys)}) share only {len(paired)} seed(s) after "
                    f"matching by seed id; dropped mismatched/missing seeds."
                )
            test = paired_bootstrap_test(
                paired["top1_arm"].to_numpy(), paired["top1_ref"].to_numpy(), n_boot=n_boot
            )
            sig_col.append(f"p={test['p_value']:.3f}{'*' if test['significant_at_0.05'] else ''}")
        out_df[f"top1_vs_{reference_mode}"] = sig_col

    try:
        md = out_df.to_markdown(index=False)
    except ImportError:
        md = out_df.to_string(index=False)
    # Any provenance judgement that let this table be built travels WITH the
    # table. A rationale that lives only in a config file and a terminal
    # scrollback is one that a reader of the published numbers never sees.
    if provenance_notes:
        md += "\n\nProvenance\n" + "\n".join(f"- {n}" for n in provenance_notes)
    out_path = Path(out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(md + "\n", encoding="utf-8")
    csv_path = out_path.with_suffix(".csv")
    # The markdown keeps the human-readable "n/a", but the CSV must not: "n/a" is
    # in pandas' default NA list, so a downstream `pd.read_csv` turns it straight
    # back into NaN and any `groupby` on these columns silently drops every
    # non-fusion arm -- the exact failure documented and fixed on the way *in*
    # above, reintroduced on the way out. "none" round-trips as a plain string.
    out_df.replace({c: {"n/a": "none"} for c in group_cols}).to_csv(csv_path, index=False)
    print(md)
    print(f"Wrote {out_path} and {csv_path}")


DATASET_TITLES = {
    "beemachine": "BeeMachine Parts",
    "cub": "CUB Parts",
    "fish_vista": "Fish-Vista Parts",
}

# Per-arm facts that do not come from a results CSV: what each mechanism costs
# to serve and what it needs at inference. Used by `recommend` to turn the
# accuracy table into the mechanism-by-constraint recommendation the research
# plan asks for (Sec. 5 Stage E, Sec. 10).
ARM_PROFILE = {
    "baseline":         {"passes": 1, "needs_mask": False, "needs_desc": False},
    "capacity_matched": {"passes": 1, "needs_mask": False, "needs_desc": False},
    "heavy_aug":        {"passes": 1, "needs_mask": False, "needs_desc": False},
    "masked":           {"passes": 1, "needs_mask": True,  "needs_desc": False},
    "multitask":        {"passes": 1, "needs_mask": False, "needs_desc": False},
    "concat":           {"passes": 1, "needs_mask": True,  "needs_desc": True},
    "gated_residual":   {"passes": 1, "needs_mask": True,  "needs_desc": True},
    "descriptors_only": {"passes": 0, "needs_mask": True,  "needs_desc": True},
    "partcrop":         {"passes": "K+1", "needs_mask": True, "needs_desc": False},
    "attention_parts":  {"passes": "K+1", "needs_mask": True, "needs_desc": True},
}


def _read_ablation_csvs(paths):
    """Load one or more per-dataset ablation_table.csv into a single frame."""
    frames = []
    for p in paths:
        path = Path(p)
        if not path.is_file():
            print(f"[pooled] skipping missing {path}")
            continue
        df = pd.read_csv(path, keep_default_na=False)
        # `dataset` is not a column of the per-dataset table; recover it from
        # the path (outputs/{dataset}/stage_e/ablation_table.csv).
        parts = path.resolve().parts
        ds = parts[parts.index("outputs") + 1] if "outputs" in parts else path.stem
        df["dataset"] = ds
        frames.append(df)
    if not frames:
        raise SystemExit("No ablation_table.csv found; run `ablation_table` first.")
    return pd.concat(frames, ignore_index=True)


def cmd_pooled_table(inputs: list[str], out: str, metric: str = "top1_mean"):
    """Cross-dataset view: one row per (arm, descriptor group), one column per
    dataset, plus the mean rank across datasets.

    Rank, not raw accuracy, is the pooled summary. Averaging top-1 across
    Beemachine (160 classes), CUB (199) and Fish-Vista (1,758) would be
    meaningless -- the numbers are not on a common scale and the mean would be
    dominated by whichever corpus happens to be easiest. Mean rank answers the
    question the plan actually asks (H1: is there a universal winner?) and is
    invariant to that.
    """
    df = _read_ablation_csvs(inputs)
    if metric not in df.columns:
        raise SystemExit(f"{metric} not in {sorted(df.columns)}")
    keys = [c for c in ("mode", "group") if c in df.columns]
    # One number per (dataset, arm, group): the best cell across mask sources
    # and backbones, i.e. each arm shown at its own best configuration.
    best = df.groupby(["dataset"] + keys)[metric].max().reset_index()
    best["rank"] = best.groupby("dataset")[metric].rank(ascending=False, method="min")

    wide = best.pivot_table(index=keys, columns="dataset", values=metric)
    ranks = best.pivot_table(index=keys, columns="dataset", values="rank")
    wide["mean_rank"] = ranks.mean(axis=1).round(2)
    wide["n_datasets"] = ranks.notna().sum(axis=1)
    wide = wide.sort_values("mean_rank").round(4).reset_index()

    out_path = Path(out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    wide.to_csv(out_path.with_suffix(".csv"), index=False)
    try:
        md = wide.to_markdown(index=False)
    except ImportError:
        md = wide.to_string(index=False)
    note = (
        f"\nCells are the best {metric} for that arm on that dataset, across mask "
        "sources and backbones. `mean_rank` averages within-dataset ranks and is "
        "the pooled summary: raw accuracy is not comparable across corpora with "
        "160 / 199 / 1,758 classes.\n"
    )
    out_path.write_text(md + "\n" + note, encoding="utf-8")
    print(md + note)
    print(f"Wrote {out_path} and {out_path.with_suffix('.csv')}")


def cmd_recommend(inputs: list[str], out: str, reference_mode: str = "baseline"):
    """The mechanism-by-constraint recommendation table (research plan Sec. 7).

    Deliberately mechanical: for each operating constraint it selects the arm
    that maximises the relevant metric among the arms that satisfy the
    constraint, and reports the margin over the whole-image reference. If the
    best arm under a constraint is the reference itself, that is what gets
    recommended -- the plan's stated risk is that a "no clear winner" result
    reads as a weak paper, and the mitigation is to report it plainly.
    """
    df = _read_ablation_csvs(inputs)
    metric = "top1_mean"
    if metric not in df.columns:
        raise SystemExit(f"{metric} not in {sorted(df.columns)}")

    def profile(mode):
        return ARM_PROFILE.get(str(mode), {"passes": "?", "needs_mask": None, "needs_desc": None})

    def single_pass(mode):
        return profile(mode)["passes"] == 1

    def maskless(mode):
        return profile(mode)["needs_mask"] is False

    constraints = [
        ("No constraint", lambda m: True),
        ("Compute-constrained (1 backbone pass/image)", single_pass),
        ("No segmenter available at serving time", maskless),
        ("Masks unreliable (predicted/pseudo only)", lambda m: True),
    ]

    rows = []
    for ds, g in df.groupby("dataset"):
        ref = g[g["mode"] == reference_mode][metric]
        ref_val = float(ref.max()) if len(ref) else float("nan")
        for label, ok in constraints:
            sub = g[g["mode"].map(ok)]
            if label.startswith("Masks unreliable") and "mask_source" in g.columns:
                sub = sub[sub["mask_source"].isin(["pred", "pseudo", "n/a", "none"])]
            if not len(sub):
                continue
            best = sub.loc[sub[metric].idxmax()]
            rows.append(
                {
                    "dataset": ds,
                    "constraint": label,
                    "recommended_arm": best["mode"],
                    "descriptor_group": best.get("group", ""),
                    "mask_source": best.get("mask_source", ""),
                    "top1": round(float(best[metric]), 4),
                    "vs_reference": round(float(best[metric]) - ref_val, 4),
                    "passes_per_image": profile(best["mode"])["passes"],
                }
            )
    out_df = pd.DataFrame(rows)
    out_path = Path(out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_df.to_csv(out_path.with_suffix(".csv"), index=False)
    try:
        md = out_df.to_markdown(index=False)
    except ImportError:
        md = out_df.to_string(index=False)
    note = (
        f"\n`vs_reference` is the top-1 margin over the `{reference_mode}` arm on the "
        "same dataset. A non-positive margin means no arm satisfying that constraint "
        "beat the whole-image reference, which is a result, not a gap in the table.\n"
    )
    out_path.write_text(md + "\n" + note, encoding="utf-8")
    print(md + note)
    print(f"Wrote {out_path} and {out_path.with_suffix('.csv')}")


def contract_dir(cfg) -> Path:
    """Home for the pre-Stage-A artifacts.

    Deliberately not `stage_e/`: these are written *before* Stage A, and
    `stage_e/` means "reporting tables built from results". Nor
    `frozen_splits/`, which holds the git-tracked split JSONs and nothing else.
    """
    return Path(cfg["paths"]["output_root"]) / "contract"


def cmd_contract(cfg, config_path: str, force: bool = False):
    """Write the study pre-registration, once, before Stage A.

    This is a commitment record, not a report: it is written a single time and
    refuses to overwrite itself, because a "contract" that silently re-dates on
    every pipeline run pre-registers nothing. Use --force to deliberately
    re-lock after an intentional protocol change.
    """
    backbones = cfg["classification"]["backbones"]
    bins = cfg["metrics"]["long_tail_bins"]
    # `long_tail_bins` may be explicit integer edges or the string "quantile"
    # (edges derived per corpus at equal class quantiles -- see
    # metrics.quantile_long_tail_edges). Rendering assumed exactly three
    # integers, which is not something a pre-registration template should
    # require of a config value.
    if isinstance(bins, str):
        bin_desc = f"{bins} (derived per corpus from training-set class frequencies)"
    else:
        edges = [int(b) for b in bins]
        parts = [f"<{edges[0]}"]
        parts += [f"{lo}–{hi - 1}" for lo, hi in zip(edges, edges[1:])]
        parts.append(f">={edges[-1]}")
        bin_desc = " / ".join(parts)
    dataset = cfg.get("dataset", "beemachine")
    out = contract_dir(cfg) / "study_contract.md"
    if out.exists() and not force:
        raise SystemExit(
            f"{out} already exists (locked). The contract is a pre-registration and is\n"
            "written once; pass --force only to deliberately re-lock after a protocol change."
        )

    contract = CONTRACT.format(
        today=date.today().isoformat(),
        config_path=config_path,
        config_sha=_sha256(Path(config_path)),
        dataset=dataset,
        dataset_title=DATASET_TITLES.get(dataset, dataset),
        partwhole=cfg["paths"]["partwhole_root"],
        large=cfg["paths"]["large_cls_root"],
        output_root=cfg["paths"]["output_root"],
        split_file=cfg["splits"]["filename"],
        cls_split_file=cfg["splits"].get("cls_filename", "splits_cls_seed42.json"),
        split_policy=cfg.get("split_policy", "stratified_freeze"),
        image_size=cfg["image_size"],
        cls_image_size=cfg["cls_image_size"],
        iqa_metrics=", ".join(cfg["descriptors"].get("learned_iqa_metrics") or ["(none)"]),
        part_labels=" / ".join(cfg.get("part_labels") or []),
        n_backbones=len(backbones),
        backbones=", ".join(f"`{b}`" for b in backbones),
        backbone_list="\n".join(f"- `{b}`" for b in backbones),
        metrics=", ".join(cfg["metrics"]["primary"]),
        bins=bin_desc,
        fusion_modes=", ".join(cfg["descriptors"]["fusion_modes"]),
    )
    ensure_dir(out.parent)
    out.write_text(contract, encoding="utf-8")
    print(f"Locked study contract → {out}")


def _preflight_checks(cfg) -> list[tuple[bool, str, bool]]:
    """Verify on disk what the contract only promises.

    Returns (ok, description, blocking) triples. *Blocking* checks are inputs
    Stage A cannot run without — a missing one always fails the command, since
    catching it here costs seconds instead of surfacing as a crash tens of
    GPU-hours into a sweep. Non-blocking checks are protocol requirements that
    are reported but do not stop the command.
    """
    entry = cfg.get("dataset_entry") or {}
    part_root = Path(cfg["paths"]["partwhole_root"])
    large_root = Path(cfg["paths"]["large_cls_root"])
    checks: list[tuple[bool, str, bool]] = [
        (part_root.is_dir(), f"Part–whole root exists: `{part_root}`", True),
        (large_root.is_dir(), f"Large classification root exists: `{large_root}`", True),
    ]

    for kind in ("part", "cls"):
        path = frozen_split_path(cfg, kind=kind)
        checks.append((path.is_file(), f"Frozen {kind} split present: `{path}`", True))

    if entry.get("use_train_aug", True):
        for key in ("train_aug_images_subdir", "train_aug_masks_subdir"):
            sub = entry.get(key)
            if not sub:
                checks.append((False, f"`{key}` not configured for this dataset", True))
                continue
            path = part_root / sub
            checks.append(
                (path.is_dir(), f"Train-only augmentation dir present: `{path}`", True)
            )

    labels = list(cfg.get("part_labels") or [])
    checks.append(
        (len(labels) >= 2, f"Part labels configured ({len(labels)}): {', '.join(labels)}", True)
    )

    # Every dataset carries the full CI / paired-significance grid, so every
    # dataset is held to the same >=3 seeds. A dataset that drops below this
    # yields cells with no interval and no paired test, which the paper's
    # tables have no column for.
    seeds = list(cfg.get("seeds") or [])
    checks.append(
        (
            len(seeds) >= 3,
            f"At least 3 seeds for {cfg.get('dataset')} (got {seeds or 'none'})",
            False,
        )
    )
    return checks


def cmd_preflight(cfg, strict: bool = True):
    """Check the contract's data commitments against the filesystem.

    Exits non-zero on failure so a pipeline runner stops here rather than at
    whichever later stage first touches the missing input. ``strict=False``
    downgrades the non-blocking protocol checks to warnings; blocking ones
    still fail.
    """
    checks = _preflight_checks(cfg)
    dataset = cfg.get("dataset", "beemachine")
    blocking_failures = [desc for ok, desc, blocking in checks if not ok and blocking]
    advisory_failures = [desc for ok, desc, blocking in checks if not ok and not blocking]
    fatal = blocking_failures + (advisory_failures if strict else [])

    lines = [
        f"# Preflight — {DATASET_TITLES.get(dataset, dataset)}",
        "",
        f"Checked: {date.today().isoformat()}",
        f"Result: **{'PASS' if not fatal else f'FAIL ({len(fatal)} of {len(checks)})'}**",
        "",
        "Verified against the filesystem, unlike the commitments in "
        "`study_contract.md`, which this checks.",
        "",
    ]
    lines += [
        f"- [{'x' if ok else ' '}] {desc}{'' if blocking else '  *(protocol, non-blocking)*'}"
        for ok, desc, blocking in checks
    ]
    report = "\n".join(lines) + "\n"

    out = contract_dir(cfg) / "preflight.md"
    ensure_dir(out.parent)
    out.write_text(report, encoding="utf-8")
    print(report)
    print(f"Wrote {out}")

    if advisory_failures and not strict:
        print("WARNING (non-blocking):\n- " + "\n- ".join(advisory_failures))
    if fatal:
        raise SystemExit(
            "Preflight failed:\n- " + "\n- ".join(fatal)
            + "\n\nFix these inputs before running Stage A."
        )


def cmd_repro_pack(cfg, config_path: str):
    stamp = date.today().isoformat()
    pack = Path(cfg["paths"]["output_root"]) / "stage_f" / f"repro_pack_{stamp}"
    if pack.exists():
        shutil.rmtree(pack)
    pack.mkdir(parents=True)

    # Keep the config's own basename, so a bundle records which configuration
    # produced it. If the config extends a base, that base is part of the
    # effective config too.
    config_path = Path(config_path)
    shutil.copy2(config_path, pack / config_path.name)
    for extra in _config_chain(config_path)[1:]:
        shutil.copy2(extra, pack / extra.name)

    for kind in ("part", "cls"):
        split = frozen_split_path(cfg, kind=kind)
        if split.exists():
            dest = pack / "splits" / split.name
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(split, dest)

    out_root = Path(cfg["paths"]["output_root"])
    for meta in out_root.glob("**/run_meta.json"):
        rel = meta.relative_to(out_root)
        dest = pack / "metas" / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(meta, dest)

    for name in ("best_model.json", "sweep_summary.json"):
        p = out_root / "stage_a" / name
        if p.exists():
            dest = pack / "stage_a" / name
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(p, dest)

    # The pre-registration and the reporting tables are the two things a
    # reader needs to check the claims against; a bundle without them
    # documents how the runs were configured but not what was concluded.
    for src_dir, dest_name in ((contract_dir(cfg), "contract"), (out_root / "stage_e", "stage_e")):
        if src_dir.is_dir():
            for item in sorted(src_dir.iterdir()):
                if item.is_file():
                    dest = pack / dest_name / item.name
                    dest.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(item, dest)

    zip_path = shutil.make_archive(str(pack), "zip", root_dir=pack)
    shutil.rmtree(pack)
    print(f"Repro pack → {zip_path}")


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def cmd_hash_ckpts(glob_pat: str, out: str):
    lines = []
    for p in sorted(glob(glob_pat, recursive=True)):
        path = Path(p)
        if not path.is_file():
            continue
        digest = _sha256(path)
        lines.append(f"{digest}  {path}")
        print(lines[-1])
    out_path = Path(out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")
    print(f"Wrote {out_path}")


def main():
    ap = argparse.ArgumentParser(
        description="Pre-registration (contract, preflight) + Stage E/F reporting and reproducibility"
    )
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("seg_table")
    add_global_stage_args(p)
    p.add_argument("--summary", default=None)
    p.add_argument("--out", default=None)

    p = sub.add_parser("ablation_table")
    add_global_stage_args(p)
    p.add_argument("--fusion_summary", required=True)
    p.add_argument("--out", default=None)
    p.add_argument(
        "--reference_mode",
        default="concat",
        help="Arm to test every other arm against (paired bootstrap on top1).",
    )
    p.add_argument(
        "--allow_mixed",
        action="store_true",
        help="Build the table even when rows span multiple code versions or "
        "include descriptor rows written before the z-scoring fix. Off by "
        "default: mixing those is how a table stops being a comparison.",
    )

    p = sub.add_parser(
        "pooled_table",
        help="Cross-dataset comparison (mean rank) from per-dataset ablation_table.csv files.",
    )
    add_global_stage_args(p)
    p.add_argument("--inputs", nargs="+", required=True)
    p.add_argument("--out", default=None)
    p.add_argument("--metric", default="top1_mean")

    p = sub.add_parser(
        "recommend",
        help="Mechanism-by-constraint recommendation table (research plan Sec. 7).",
    )
    add_global_stage_args(p)
    p.add_argument("--inputs", nargs="+", required=True)
    p.add_argument("--out", default=None)
    p.add_argument("--reference_mode", default="baseline")

    p = sub.add_parser("contract", help="Lock the study pre-registration (once, before Stage A).")
    add_global_stage_args(p)
    p.add_argument(
        "--force",
        action="store_true",
        help="Re-lock an existing contract after a deliberate protocol change.",
    )

    p = sub.add_parser("preflight", help="Verify the contract's data commitments on disk.")
    add_global_stage_args(p)
    p.add_argument(
        "--no-strict",
        dest="strict",
        action="store_false",
        help="Report failures without exiting non-zero.",
    )

    p = sub.add_parser("repro_pack")
    add_global_stage_args(p)

    p = sub.add_parser("hash_ckpts")
    add_global_stage_args(p)
    p.add_argument("--glob", required=True)
    p.add_argument("--out", default=None)

    args = ap.parse_args()
    cfg = load_config(args.config, dataset=args.dataset, protocol=getattr(args, "protocol", None))
    out_root = Path(cfg["paths"]["output_root"])

    if args.cmd == "seg_table":
        out = args.out or str(stage_run_dir(cfg, "stage_e", "seg_comparison_table.md"))
        cmd_seg_table(cfg, args.summary, out)
    elif args.cmd == "ablation_table":
        out = args.out or str(stage_run_dir(cfg, "stage_e", "ablation_table.md"))
        cmd_ablation_table(
            args.fusion_summary, out,
            reference_mode=args.reference_mode,
            n_boot=int(cfg["metrics"]["bootstrap_n"]),
            allow_mixed=args.allow_mixed,
            dataset=cfg["dataset"],
        )
    elif args.cmd == "pooled_table":
        out = args.out or str(Path("outputs") / "pooled" / "pooled_table.md")
        cmd_pooled_table(args.inputs, out, metric=args.metric)
    elif args.cmd == "recommend":
        out = args.out or str(Path("outputs") / "pooled" / "recommendation_table.md")
        cmd_recommend(args.inputs, out, reference_mode=args.reference_mode)
    elif args.cmd == "contract":
        cmd_contract(cfg, args.config, force=args.force)
    elif args.cmd == "preflight":
        cmd_preflight(cfg, strict=args.strict)
    elif args.cmd == "repro_pack":
        cmd_repro_pack(cfg, args.config)
    elif args.cmd == "hash_ckpts":
        out = args.out or str(out_root / "stage_f" / "checkpoint_hashes.txt")
        cmd_hash_ckpts(args.glob, out)


if __name__ == "__main__":
    main()
